# Generated by Django 5.1.1 on 2025-11-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_make_address_optional'),
        ('orders', '0004_auto_20251101_2034'),
    ]

    operations = [
    ]
