# Generated by Django 5.2.7 on 2025-10-31 22:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم العلامة التجارية')),
                ('slug', models.SlugField(help_text='يتم إنشاؤه تلقائياً من الاسم', max_length=200, unique=True, verbose_name='الاسم اللطيف')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='الشعار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(help_text='يتم إنشاؤه تلقائياً من الاسم', max_length=200, unique=True, verbose_name='الاسم اللطيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='الفئة الأب')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(help_text='يتم إنشاؤه تلقائياً من الاسم', max_length=300, unique=True, verbose_name='الاسم اللطيف')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='رمز المنتج (SKU)')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='وصف مختصر')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='سعر التخفيض')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='للاستخدام الداخلي فقط', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر التكلفة')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='حد المخزون المنخفض')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الوزن (كجم)')),
                ('dimensions', models.CharField(blank=True, help_text='مثال: 10x5x3 سم', max_length=100, verbose_name='الأبعاد')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='الصورة الرئيسية')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الثانية')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الثالثة')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الرابعة')),
                ('compatible_makes', models.CharField(blank=True, help_text='مثال: تويوتا، نيسان، هيونداي', max_length=500, verbose_name='الماركات المتوافقة')),
                ('compatible_models', models.CharField(blank=True, help_text='مثال: كامري 2015-2020، التيما 2018-2022', max_length=500, verbose_name='الموديلات المتوافقة')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='من سنة')),
                ('year_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='إلى سنة')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان الميتا')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='وصف الميتا')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_new_arrival', models.BooleanField(default=False, verbose_name='وصل حديثاً')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.brand', verbose_name='العلامة التجارية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المواصفة')),
                ('value', models.CharField(max_length=500, verbose_name='القيمة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مواصفة المنتج',
                'verbose_name_plural': 'مواصفات المنتجات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='من 1 إلى 5 نجوم', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='هل اشترى المستخدم هذا المنتج؟', verbose_name='مشتري موثق')),
                ('is_approved', models.BooleanField(default=True, help_text='يجب الموافقة على المراجعة قبل عرضها', verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
