# Generated by Django 5.2.6 on 2025-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text='المنتجات القادمة قريباً', verbose_name='قريباً'),
        ),
    ]
