# Generated by Django 5.2.6 on 2025-11-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_coming_soon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='العنوان الفرعي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(help_text='يُفضل استخدام صور بحجم 1920x600 للبانر الرئيسي', upload_to='advertisements/', verbose_name='الصورة')),
                ('mobile_image', models.ImageField(blank=True, help_text='صورة مخصصة للأجهزة المحمولة (اختياري)', null=True, upload_to='advertisements/', verbose_name='صورة الموبايل')),
                ('link_url', models.URLField(blank=True, help_text='الرابط عند الضغط على الإعلان', verbose_name='رابط الإعلان')),
                ('link_text', models.CharField(blank=True, default='تسوق الآن', max_length=100, verbose_name='نص الزر')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='فتح في تبويب جديد')),
                ('placement', models.CharField(choices=[('hero', 'البانر الرئيسي (Hero)'), ('sidebar', 'الشريط الجانبي'), ('middle', 'منتصف الصفحة'), ('footer', 'أسفل الصفحة'), ('popup', 'نافذة منبثقة')], default='hero', max_length=20, verbose_name='موقع العرض')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='الترتيب في حالة وجود أكثر من إعلان (الأقل يظهر أولاً)', verbose_name='ترتيب العرض')),
                ('start_date', models.DateTimeField(blank=True, help_text='تاريخ بدء عرض الإعلان (اختياري)', null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, help_text='تاريخ انتهاء عرض الإعلان (اختياري)', null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('click_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد النقرات')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['placement', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='الصورة')),
                ('thumbnail', models.ImageField(blank=True, help_text='سيتم إنشاؤها تلقائياً إذا تُركت فارغة', null=True, upload_to='gallery/thumbnails/', verbose_name='الصورة المصغرة')),
                ('category', models.CharField(choices=[('workshop', 'ورشة العمل'), ('products', 'المنتجات'), ('events', 'الفعاليات'), ('customers', 'العملاء'), ('team', 'الفريق'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الفئة')),
                ('tags', models.CharField(blank=True, help_text='افصل بين الوسوم بفاصلة (مثال: سيارات، قطع غيار، تويوتا)', max_length=500, verbose_name='الوسوم')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_featured', models.BooleanField(default=False, help_text='عرض في الصفحة الرئيسية', verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صورة معرض',
                'verbose_name_plural': 'معرض الصور',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
