# Generated by Django 5.2.6 on 2025-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_advertisement_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(help_text='يتم إنشاؤه تلقائياً من الاسم', max_length=200, unique=True, verbose_name='رابط العلامة التجارية (Slug)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='يتم إنشاؤه تلقائياً من الاسم', max_length=200, unique=True, verbose_name='رابط الفئة (Slug)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='يتم إنشاؤه تلقائياً من الاسم', max_length=300, unique=True, verbose_name='رابط المنتج (Slug)'),
        ),
    ]
