# Generated by Django 5.2.6 on 2025-11-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='اسم أيقونة SVG أو Emoji (اختياري)', max_length=100, verbose_name='رمز الأيقونة'),
        ),
        migrations.AddField(
            model_name='category',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='ترتيب عرض الفئة في القائمة الرئيسية (الأصغر أولاً)', verbose_name='ترتيب القائمة'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='حدد هذا الخيار لإظهار الفئة في القائمة الرئيسية (Mega Menu)', verbose_name='إظهار في القائمة الرئيسية'),
        ),
    ]
