# Generated by Django 5.1.1 on 2025-11-09 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_icon_category_menu_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compatible_makes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compatible_models',
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_brands',
            field=models.ManyToManyField(blank=True, related_name='compatible_products', to='store.brand', verbose_name='الماركات المتوافقة'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموديل')),
                ('slug', models.SlugField(help_text='يتم إنشاؤه تلقائياً من الماركة والموديل', max_length=150, unique=True, verbose_name='رابط الموديل (Slug)')),
                ('year_from', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='من سنة')),
                ('year_to', models.PositiveIntegerField(blank=True, help_text='اتركه فارغاً إذا كان الموديل لا يزال يُنتج', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='إلى سنة')),
                ('generation', models.CharField(blank=True, help_text='مثل: الجيل الثالث، الجيل الرابع', max_length=50, verbose_name='الجيل')),
                ('body_type', models.CharField(blank=True, help_text='مثل: سيدان، هاتشباك، SUV', max_length=50, verbose_name='نوع الهيكل')),
                ('engine_types', models.CharField(blank=True, help_text='مثل: 1.6L, 2.0L, 2.4L', max_length=200, verbose_name='أنواع المحركات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_models/', verbose_name='صورة الموديل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='store.brand', verbose_name='الماركة')),
            ],
            options={
                'verbose_name': 'موديل السيارة',
                'verbose_name_plural': 'موديلات السيارات',
                'ordering': ['brand__name', 'name', '-year_from'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_car_models',
            field=models.ManyToManyField(blank=True, related_name='compatible_products', to='store.carmodel', verbose_name='الموديلات المتوافقة'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['brand', 'is_active'], name='store_carmo_brand_i_536a65_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['year_from', 'year_to'], name='store_carmo_year_fr_c11419_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'name', 'year_from')},
        ),
    ]
