# Generated by Django 5.1.1 on 2025-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_compatible_makes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_in_navbar',
            field=models.BooleanField(default=False, help_text='حدد هذا الخيار لإظهار العلامة التجارية في شريط التنقل العلوي', verbose_name='إظهار في شريط التنقل'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='show_in_navbar',
            field=models.BooleanField(default=False, help_text='حدد هذا الخيار لإظهار الموديل في شريط التنقل العلوي', verbose_name='إظهار في شريط التنقل'),
        ),
    ]
