# Generated by Django 5.2.7 on 2025-11-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='SAR', max_length=3, verbose_name='العملة'),
        ),
    ]
