# Generated by Django 5.2.7 on 2025-11-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity', verbose_name='Quantity')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Minimum quantity before low stock alert', verbose_name='Low Stock Threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['product__name'],
                'indexes': [models.Index(fields=['product'], name='inventory_i_product_8c36d3_idx'), models.Index(fields=['quantity'], name='inventory_i_quantit_82f142_idx')],
            },
        ),
    ]
