"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-wiijaxo4^c=ge!_@bw8p290p8#dwa!0=atatkmrsk+p!#fnqoh')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Allowed Hosts
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF Trusted Origins (for PythonAnywhere and production)
CSRF_TRUSTED_ORIGINS = [
    'https://empire77.pythonanywhere.com',
]


# Application definition

INSTALLED_APPS = [
    'django_daisy',
    # 'jazzmin',
    # 'jet',
    'django.contrib.admin',
    'django.contrib.humanize',  
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "django_htmx",
    "tailwind",
    # Our custom apps
    'apps.users',
    'apps.store',
    'apps.orders',
    'apps.inventory',
    'apps.payments',
    'apps.dashboard',
    # ... any other apps you made ...
]

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Login/Logout URLs
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'store:product_list'
LOGOUT_REDIRECT_URL = 'store:product_list'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',  # HTMX middleware
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        # This tells Django to look in the root 'templates/' folder
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        
        # This tells Django to look inside each app's 'templates/' folder
        'APP_DIRS': True, 
        
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.orders.context_processors.cart_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Configure the static files location (for Tailwind output)
STATIC_URL = 'static/'

# This tells Django where to *find* compiled static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# This is where 'collectstatic' will put all files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Stripe Configuration
# Get these from your Stripe Dashboard: https://dashboard.stripe.com/apikeys
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', 'pk_test_your_publishable_key_here')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', 'sk_test_your_secret_key_here')
# Webhook secret for verifying webhook signatures from Stripe
# Get this from: https://dashboard.stripe.com/webhooks
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', 'whsec_your_webhook_secret_here')

# ============================================================================
# Email Configuration
# ============================================================================

# Email Backend
# For development: Use console backend (prints emails to terminal)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production: Use SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'ramzihaidan537@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # IMPORTANT: Use App Password from .env file!
    
# Default From Email
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Gulf Emperor <noreply@gulfemperor.com>')

# ============================================================================
# Django Daisy (Admin Panel) Configuration
# ============================================================================
DAISY_SETTINGS = {
    # Branding
    'SITE_TITLE': 'إمبراطور الخليج',
    'SITE_HEADER': 'إدارة إمبراطور الخليج',
    'INDEX_TITLE': 'مرحباً بك في لوحة التحكم',
    'SITE_LOGO': '/static/img/logo.png',  # Update with your actual logo path
    
    # Customization
    'EXTRA_STYLES': [
        # '/static/css/output.css',  # Your Tailwind CSS with DaisyUI
    ],
    'EXTRA_SCRIPTS': [],
    'LOAD_FULL_STYLES': True,  # Load complete DaisyUI library
    'SHOW_CHANGELIST_FILTER': True,  # Auto-open filter sidebar
    'DONT_SUPPORT_ME': True,  # Hide GitHub link
    'SIDEBAR_FOOTNOTE': '© 2025 إمبراطور الخليج - جميع الحقوق محفوظة',
    
    # Theme Configuration
    'DEFAULT_THEME': 'gulfemperor',  # Your custom theme
    'DEFAULT_THEME_DARK': 'dark',
    'SHOW_THEME_SELECTOR': True,
    'THEME_LIST': [
        {'name': 'فاتح', 'value': 'light'},
        {'name': 'داكن', 'value': 'dark'},
    ],
    
    # Third-Party App Customization (Django built-in apps)
    'APPS_REORDER': {
        'auth': {
            'hide': True,  # Hide auth app (users managed in custom users app)
        },
        'contenttypes': {
            'hide': True,  # Hide content types from sidebar
        },
        'sessions': {
            'hide': True,  # Hide sessions from sidebar
        },
        'apps.dashboard': {
            'icon': 'fa-solid fa-gauge',
            'name': 'لوحة التحكم',
            'hide': True,
            'divider_title': "لوحة التحكم",
            'priority': 200,
        },
    },
}
